import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Text,
} from "@react-email/components";

interface NotesReadyProps {
  patientName: string;
  notesLink: string;
}

export function NotesReady({ patientName, notesLink }: NotesReadyProps) {
  return (
    <Html>
      <Head />
      <Preview>Session notes ready for {patientName}</Preview>
      <Body
        style={{
          backgroundColor: "#F6F3EE",
          fontFamily: "Instrument Sans, Arial, sans-serif",
          margin: 0,
          padding: 0,
        }}
      >
        <Container
          style={{
            maxWidth: "480px",
            margin: "40px auto",
            backgroundColor: "#ffffff",
            borderRadius: "12px",
            padding: "32px",
          }}
        >
          <Heading
            style={{
              color: "#00595c",
              fontSize: "24px",
              fontWeight: "700",
              margin: "0 0 16px",
              lineHeight: "1.2",
            }}
          >
            Session Notes Ready
          </Heading>

          <Text
            style={{
              fontSize: "16px",
              color: "#374151",
              lineHeight: "1.6",
              margin: "0 0 24px",
            }}
          >
            AI-generated notes for your session with {patientName} are ready for
            review. Please check them for accuracy before sharing or filing.
          </Text>

          <Button
            href={notesLink}
            style={{
              backgroundColor: "#00595c",
              color: "#ffffff",
              padding: "12px 24px",
              borderRadius: "8px",
              textDecoration: "none",
              display: "inline-block",
              fontSize: "16px",
              fontWeight: "600",
            }}
          >
            Review Notes
          </Button>

          <Hr
            style={{
              borderColor: "#e5e7eb",
              margin: "32px 0 24px",
            }}
          />

          <Text
            style={{
              fontSize: "13px",
              color: "#9ca3af",
              margin: 0,
              lineHeight: "1.5",
            }}
          >
            These notes were generated by AI and may require edits. Always
            review before use. You received this email from Vocali.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

export default NotesReady;
