import { ConvexHttpClient } from "convex/browser";

import { api } from "../../../../../convex/_generated/api";

function getConvexClient() {
  const url = process.env.NEXT_PUBLIC_CONVEX_URL;
  if (!url) throw new Error("NEXT_PUBLIC_CONVEX_URL is not set");
  return new ConvexHttpClient(url);
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  if (!slug) {
    return new Response("Not found", { status: 404 });
  }

  try {
    const convex = getConvexClient();
    const html = await convex.query(api.generated_files.getPublicBundle, {
      shareSlug: slug,
    });

    if (!html) {
      return new Response("Not found", { status: 404 });
    }

    // CSP trade-off: unsafe-inline required because Parcel bundles inline <script> tags.
    // Mitigations: (1) HTML is AI-generated by Claude, not user-authored
    // (2) stored in Convex, not user-uploaded (3) connect-src 'none' blocks all network
    // (4) frame-ancestors 'self' prevents third-party embedding.
    // To eliminate unsafe-inline: configure Parcel to extract scripts to separate files.
    return new Response(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Cache-Control": "public, max-age=60, s-maxage=300",
        "Content-Security-Policy": "default-src 'none'; script-src 'unsafe-inline' https://cdn.tailwindcss.com; style-src 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src blob: data: https:; connect-src 'none'; frame-ancestors 'self';",
      },
    });
  } catch (error) {
    console.error("[api/tool] Failed to serve bundle:", error);
    return new Response("Internal server error", { status: 500 });
  }
}
