export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  BUILDER: "/builder",
  BUILDER_SESSION: (sessionId: string) => `/builder/${sessionId}` as const,
  MY_TOOLS: "/my-tools",
  TEMPLATES: "/templates",
  FLASHCARDS: "/flashcards",
  SETTINGS: "/settings",
  TOOL_VIEW: (toolId: string) => `/tool/${toolId}` as const,
  PATIENTS: "/patients",
  PATIENT_DETAIL: (id: string) => `/patients/${id}` as const,
  PATIENT_NEW: "/patients/new",
  INVITE: (token: string) => `/invite/${token}` as const,
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  FAMILY: "/family",
  FAMILY_CHILD: (patientId: string) => `/family/${patientId}` as const,
  FAMILY_MESSAGES: (patientId: string) => `/family/${patientId}/messages` as const,
  FAMILY_PLAY: (patientId: string) => `/family/${patientId}/play` as const,
  FAMILY_PLAY_APP: (patientId: string, appId: string) => `/family/${patientId}/play/${appId}` as const,
} as const;
